import {test,expect} from '@playwright/test';
import {serverFor,networkOptions} from '../../src/ide/stellar.js';
test('live Testnet: automatic funding, uploaded constructor, deployment and authorized invocation',async({page})=>{
 test.skip(process.env.LIVE_TESTNET!=='1','Explicit opt-in: creates a fresh Testnet account and contract.');test.setTimeout(300000);
 const wasm=await serverFor(networkOptions[0]).getContractWasmByContractId('CDPYIUM25KL3O4EZA2QZOARMGJZ7P2XVC4Q52S5SUSZQGTMMF7NA6IGG');
 const errors=[];page.on('pageerror',error=>errors.push(error.message));
 await page.goto('/');await page.getByRole('button',{name:'Deploy',exact:true}).first().click();
 await page.getByRole('button',{name:'Generate test account',exact:true}).click();
 const selector=page.getByRole('combobox',{name:'Transaction signer'});
 await expect(selector.locator('option:checked')).toContainText('(funded)',{timeout:90000});const owner=await selector.inputValue();
 await page.getByLabel('Upload WASM',{exact:true}).setInputFiles({name:'counter.wasm',mimeType:'application/wasm',buffer:Buffer.from(wasm)});
 await page.getByLabel('Constructor argument owner',{exact:true}).fill(owner);await page.getByLabel('Constructor argument start',{exact:true}).fill('7');
 await page.getByRole('button',{name:'Deploy selected WASM'}).click();await page.getByRole('button',{name:'Confirm deployment',exact:true}).click();
 await expect(page.getByRole('textbox',{name:'Contract ID',exact:true})).toHaveValue(/^C[A-Z2-7]{55}$/,{timeout:120000});
 const id=await page.getByRole('textbox',{name:'Contract ID',exact:true}).inputValue();
 await page.getByRole('combobox',{name:'Function',exact:true}).selectOption('increment');await page.getByLabel('Argument by',{exact:true}).fill('2');
 await page.getByRole('button',{name:'Simulate',exact:true}).click();
 await expect(page.getByLabel('Return value',{exact:true})).toHaveText('9',{timeout:60000});
 await page.getByRole('button',{name:'Sign and invoke',exact:true}).click();await page.getByRole('button',{name:'Confirm invocation',exact:true}).click();
 await expect(page.getByText('Transaction confirmed',{exact:true})).toBeVisible({timeout:90000});
 await page.getByRole('combobox',{name:'Function',exact:true}).selectOption('get');await page.getByRole('button',{name:'Simulate',exact:true}).click();
 await expect(page.getByLabel('Return value',{exact:true})).toHaveText('9',{timeout:60000});
 await page.getByRole('button',{name:'Use typed arguments',exact:true}).click();await page.getByLabel('Typed arguments',{exact:true}).fill('{');await page.getByRole('button',{name:'Simulate',exact:true}).click();
 await expect(page.getByRole('region',{name:'Function output'}).getByRole('alert')).toBeVisible();await expect(page.getByRole('button',{name:'Simulate',exact:true})).toBeVisible();
 await page.getByLabel('Typed arguments',{exact:true}).fill('[]');await page.getByRole('button',{name:'Simulate',exact:true}).click();await expect(page.getByLabel('Return value',{exact:true})).toHaveText('9',{timeout:60000});
 await page.screenshot({path:'test-results/function-output.png'});
 await page.setViewportSize({width:900,height:1000});await page.getByRole('region',{name:'Function output'}).scrollIntoViewIfNeeded();await page.screenshot({path:'test-results/function-output-narrow.png'});
 expect(errors).toEqual([]);console.log('Browser-verified Testnet contract:',id);
});
